name: base-image-build
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'
      DOCKERHUB_REGISTRY:
        type: string
        required: true
      DOCKERHUB_USERNAME:
        type: string
        required: true
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Runner
        run: |
          set -x
          ## Remove files
          to_delete=(
            "/swapfile"
            "/usr/local/share/boost"
            "$AGENT_TOOLSDIRECTORY"
            "/usr/share/dotnet"
            "$ANDROID_SDK_ROOT"
            "/usr/local/lib/android"
            "$ANDROID_SDK_ROOT"
            "/usr/share/swift"
          )
          for f in ${to_delete[@]}; do
            sudo rm -rf ${f} || true
          done

          ## Clean docker
          docker system prune --all --volumes --force

      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ inputs.DOCKERHUB_REGISTRY }}
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      

      - name: Run Build Script
        run: bash ./scripts/build-images.sh ${{ inputs.app }} ${{ inputs.DOCKERHUB_REGISTRY }}/${{ inputs.DOCKERHB_USERNAME }}/
